create table public.missions (
  id bigint generated by default as identity primary key,
  mission_code text not null unique,
  title text not null,
  status text not null check (status in ('PLANNED','IN_PROGRESS','COMPLETED')),
  proof_url text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.missions enable row level security;

create policy "public can read mission log"
on public.missions
for select
to anon
using (true);
